KS-10-1 dice game
iggorbunov/KotlinSprint pull request #46
Opened 2024-05-30 22:52 UTC by iggorbunov

2024-05-30 23:04 UTC, ievetrovdev requested changes

2024-05-31 08:33 UTC, iggorbunov commented on src/main/kotlin/lesson_1_10/lesson_10/lesson10_task1.kt
> +}
Не понимаю как с помощью when реализовать обработку ничьи, поэтому решил реализовать таким образом
Учел комментарий про использование {} в if

2024-05-31 14:52 UTC, ievetrovdev requested changes
Ответил, попробуй дожать уже, все получится!

2024-06-01 10:35 UTC, ievetrovdev approved these changes
Отличное решение!

2024-06-02 10:27 UTC, merged